#!/bin/sh
#
## setup links to files
ln -sf vendor/jeffbritts/valet-install/vp vp;
ln -s vendor/jeffbritts/valet-install/.vscode .vscode;
ln -s vendor/jeffbritts/valet-install/.env.sample .env.sample
ln -s vendor/jeffbritts/valet-install/LocalValetDriver.php LocalValetDriver.php
ln -s vendor/jeffbritts/valet-install/npm-shrinkwrap.json npm-shrinkwrap.json
ln -s vendor/jeffbritts/valet-install/npm-shrinkwrap.json npm-shrinkwrap.json
phpcs --config-set installed_paths ../../magento/magento-coding-standard/
### this is for copying my local .env file so it is not in source control
### you can do somthing similar
cp ~/sites/vp/.env .