#!/usr/bin/env bash
usage() {
  echo "Utility for using Valet + in dev with supporting apps"
  echo "Usage:  vp [action] [additional options...]"
  echo ""
  echo "Actions:"
  printf "  %-15s%-30s\n" "-i" "Install Magento"
  printf "  %-15s%-30s\n" "-c <caches>" "Clean cache. Specific cache names optional"
  printf "  %-15s%-30s\n" "-w" "Start cache-clean watcher"
  echo ""
}

installMagento(){
    chmod +x ./install
    ./install
}


if [ "$1" = "" ]; then
    usage
fi

while [ -n "$1" ]

# while loop starts

do

case "$1" in

# install

-i) installMagento ;;

# cache clean

-c) vendor/bin/cache-clean.js ;;

# cache clean watch

-w) vendor/bin/cache-clean.js --watch ;;

# The double dash which separates options from parameters

--) shift

# Exit the loop using break command

break ;;

*) usage ;;



esac

exit 0

done