#!/usr/bin/env bash
usage() {
  echo "Utility for using Valet + in dev with supporting apps\n"
  echo "Usage:\n\n  vp [action] [additional options...]"
  echo ""
  echo "Actions:\n"
  printf "  %-15s%-30s\n" "-i" "Install Magento"
  printf "  %-15s%-30s\n" "-c Clean Cache <cache names>" "Clean cache. Specific cache names optional"
  printf "  %-15s%-30s\n" "-w" "Start cache-clean watcher"
  echo ""
}

installMagento(){
    chmod +x ./install
    ./install
}

while [ -n "$1" ]

# while loop starts

do

case "$1" in

# install

-i) installMagento ;;

# cache clean

-c) vendor/bin/cache-clean.js ;;

# cache clean watch

-w) vendor/bin/cache-clean.js --watch ;;

# The double dash which separates options from parameters

--) shift

# Exit the loop using break command

break ;;

*) echo "Option $1 not recognized";;


esac

exit 0

done